export const productCategories = [
  "Fruit nectars as defined by Directive 2001/112/EC and vegetable nectars and similar products",
  "Fruit and vegetables in vinegar, oil, or brine",
  "Fruit and vegetable preparations excluding compote",
  "Processed cheese",
  "Cider and perry",
  "Potato gnocchi",
  "Mustard",
  "Aromatised wine-based drinks",
  "Processed fish and fishery products including mollusks and crustaceans",
  "Dietary foods for special medical purposes defined in Directive 1999/21/EC (excluding products from food category 13.1.5)",
  "Sauces",
  "Processed nuts",
  "Beer and malt beverages",
  "Decorations, coatings and fillings, except fruit based fillings covered by category 4.2.4",
  "Fruit juices as defined by Directive 2001/112/EC and vegetable juices",
  "Other alcoholic drinks including mixtures of alcoholic drinks with non-alcoholic drinks and spirits with less than 15 % of alcohol and",
  "Other creams",
  "Pre-cooked or processed cereals",
  "Fruit wine and made wine",
  "Food supplements supplied in a solid form including capsules and tablets and similar forms, excluding chewable forms",
  "Non heat treated processed meat",
  "Cocoa and Chocolate products as covered by Directive 2000/36/EC",
  "Desserts excluding products covered in category 1, 3 and 4",
  "Other confectionery including breath refreshening microsweets",
  "Other similar fruit or vegetable spreads",
  "Batters",
  "Fish roe",
  "Soups and broths",
  "Table Top Sweeteners in liquid form",
  "Food supplements supplied in a syrup-type or chewable form",
  "Unripened cheese excluding products falling in category 16",
  "Food supplements supplied in a liquid form",
  "Canned or bottled fruit and vegetables",
  "Jam, jellies and marmalades and sweetened chestnut puree as defined by Directive 2001/113/EC",
  "Other fat and oil emulsions including spreads as defined by Council Regulation (EC) No 1234/2007 and liquid emulsions",
  "Flavoured drinks",
  "Cheese products (excluding products falling in category 16)",
  "Dried fruit and vegetables",
  "Aromatised wines",
  "Breakfast cereals",
  "Ripened cheese",
  "Potato-, cereal-, flour- or starch-based snacks",
  "Spirit drinks as defined in Regulation (EC) No 110/2008",
  "Foods suitable for people intolerant to gluten as defined by Regulation (EC) No 41/2009",
  "Dietary foods for weight control diets intended to replace total daily food intake or an individual meal (the whole or part of the total daily diet)",
  "Heat treated processed meat",
  "Chewing gum",
  "Casings and coatings and decorations for meat",
  "Salads and savoury based sandwich spreads",
  "Edible ices",
  "Protein products, excluding products covered in category 1.8",
  "Table Top Sweeteners in powder form",
  "Salt",
  "Fine bakery wares",
  "Yeast and yeast products",
  "Table Top Sweeteners in tablets",
  "Dairy analogues, including beverage whiteners",
  "Whey cheese",
  "Unprocessed meat other than meat preparations as defined by Regulation (EC) No 853/2004",
  "Bread and rolls",
  "Flavoured fermented milk products including heat treated products",
  "Aromatised wine-product cocktails",
  "Fillings of stuffed pasta (ravioli and similar)",
  "Fats and oils essentially free from water (excluding anhydrous milkfat)",
  "Starches",
  "Nut butters and nut spreads",
  "Salt substitutes",
  "Seasonings and condiments",
  "Edible cheese rind",
  "Mead",
  "Extra jam and extra jelly as defined by Directive 2001/113/EC",
  "Dry pasta",
  "Other sugars and syrups",
  "Meat preparations as defined by Regulation (EC) No 853/2004",
  "Wine and other products defined by Regulation (EEC) No 1234/2007, and alcohol free counterparts",
  "Dietary foods for infants for special medical purposes and special formulae for infants",
  "Entire fresh fruit and vegetables",
  "Butter and concentrated butter and butter oil and anhydrous milkfat",
  "Vinegars",
  "Dehydrated milk as defined by Directive 2001/114/EC",
  "Processed eggs and egg products",
  "Noodles",
  "Unprocessed fish",
  "Processed foods not covered by categories 1 to 17, excluding foods for infants and young children",
  "Other",
  "Unprocessed molluscs and crustaceans",
  "Vegetable oil pan spray",
  "Unflavoured fermented milk products, heat-treated after fermentation",
  "Processed potato products",
  "Processed cereal-based foods and baby foods for infants and young children as defined by Directive 2006/125/EC ",
  "Follow-on formulae as defined by Directive 2006/141/EC",
  "Traditional immersion cured products (Meat products cured by immersion in a curing solution containing nitrites and/or nitrates, salt and other components)",
  "Bread prepared solely with the following ingredients: wheat flour, water, yeast or leaven,salt",
  "Unflavoured pasteurised and sterilised (including UHT) milk",
  "Dietary foods for babies and young children for special medical purposes as defined in Directive 1999/21/EC",
  "Pain courant francais; Friss b�zakeny�r, feh�r �s f�lbarna kenyerek",
  "Infant formulae as defined by Directive 2006/141/EC",
  "Traditional dry cured products. (Dry curing process involves dry application of curing mixture containing nitrites and/or nitrates, salt and other components to the surface of the meat followed by a period of stabilisation/maturation).",
  "Fresh pasta",
  "Other foods for young children",
  "Compote, excluding products covered by category 16",
  "Frozen fruit and vegetables",
  "Peeled, cut and shredded fruit and vegetables",
  "Herbs and spices",
  "Unflavoured pasteurised cream (excluding reduced fat creams)",
  "Flours and other milled products and starches",
  "Sugars and syrups as defined by Directive 2001/111/EC",
  "Other traditionally cured products. (Immersion and dry cured processes used in combination or where nitrite and/or nitrate is included in a compound product or where the curing solution is injected into the product prior to cooking)",
  "Water, including natural mineral water as defined in Directive 2009/54/EC and spring water and all other bottled or packed waters",
  "Fresh pre-cooked pasta",
  "All categories of foods",
  "Whole, broken, or flaked grain",
  "Unflavoured live fermented cream products and substitute products with a fat content of less than 20%",
  "Coffee, coffee extracts",
];
